ezplatform_page_fieldtype:
    blocks:
        contentlist:
            views:
                bike_ride_list:
                    name: 'Bike ride list of links'
                    template: '@ezdesign/blocks/contentlist.html.twig'
        random:
            name: Random Content
            thumbnail: ''
            category: 'training'
            views:
                default:
                    name: 'Default'
                    template: '@ezdesign/blocks/random.html.twig'
