ezplatform_page_fieldtype:
    blocks:
        contentlist:
            views:
                bike_ride_list:
                    name: 'Bike ride list of links'
                    template: '@ezdesign/blocks/contentlist.html.twig'
        random:
            name: Random Content
            thumbnail: ''
            category: 'training'
            views:
                default:
                    name: 'Default'
                    template: '@ezdesign/blocks/random.html.twig'
                card:
                    name: 'Card'
                    template: '@ezdesign/blocks/random_card.html.twig'
            attributes:
                content_type:
                    name: Select type of content to display
                    value: bike_ride
                    #type: contenttypelist
                    type: select
                    options:
                        multiple: false
                        choices:
                            'Bike Ride': bike_ride
                            'Point of interest': point_of_interest
