ezdesign:
    design_list:
        bike_ride: [bike_ride, simple]

ezplatform:
    system:
        site:
            design: bike_ride
            pagelayout: '@ezdesign/pagelayout.html.twig'
            content_view:
                full:
                    all_rides:
                        controller: ez_query:contentQueryAction
                        template: "@ezdesign/full/all_rides.html.twig"
                        match:
                            Id\Location: 2
                        params:
                            query:
                                query_type: BikeRideList
                                parameters:
                                    contentType: bike_ride
                                    #parentLocationId: 56
                                assign_results_to: bike_ride_list
                    bike_ride:
                        template: "@ezdesign/full/bike_ride.html.twig"
                        match:
                            Identifier\ContentType: [bike_ride]
                    point_of_interest:
                        controller: App\Controller\PointOfInterestController::pointOfInterestView
                        template: "@ezdesign/full/point_of_interest.html.twig"
                        match:
                            Identifier\ContentType: [point_of_interest]
                    simple:
                        template: "@ezdesign/full/simple.html.twig"
                        match: true
                modal:
                    point_of_interest:
                        template: "@ezdesign/modal/point_of_interest.html.twig"
                        match:
                            Identifier\ContentType: [point_of_interest]